# -*- coding: utf-8; -*-

from httpolice.common import StatusCode, RFC
from httpolice.known.base import KnownDict


def description(code):
    return known.get_info(code).get('description')


class KnownStatusCodes(KnownDict):

    @classmethod
    def _name_for(cls, item):
        return item['description']. \
            replace(u'-', u' ').replace(u' ', u'_').lower()


known = KnownStatusCodes([
 {'_': StatusCode(100),
  '_citations': [RFC(7231, section=(6, 2, 1))],
  'description': 'Continue'},
 {'_': StatusCode(101),
  '_citations': [RFC(7231, section=(6, 2, 2))],
  'description': 'Switching Protocols'},
 {'_': StatusCode(102),
  '_citations': [RFC(2518)],
  'description': 'Processing'},
 {'_': StatusCode(200),
  '_citations': [RFC(7231, section=(6, 3, 1))],
  'description': 'OK'},
 {'_': StatusCode(201),
  '_citations': [RFC(7231, section=(6, 3, 2))],
  'description': 'Created'},
 {'_': StatusCode(202),
  '_citations': [RFC(7231, section=(6, 3, 3))],
  'description': 'Accepted'},
 {'_': StatusCode(203),
  '_citations': [RFC(7231, section=(6, 3, 4))],
  'description': 'Non-Authoritative Information'},
 {'_': StatusCode(204),
  '_citations': [RFC(7231, section=(6, 3, 5))],
  'description': 'No Content'},
 {'_': StatusCode(205),
  '_citations': [RFC(7231, section=(6, 3, 6))],
  'description': 'Reset Content'},
 {'_': StatusCode(206),
  '_citations': [RFC(7233, section=(4, 1))],
  'description': 'Partial Content'},
 {'_': StatusCode(207),
  '_citations': [RFC(4918)],
  'description': 'Multi-Status'},
 {'_': StatusCode(208),
  '_citations': [RFC(5842)],
  'description': 'Already Reported'},
 {'_': StatusCode(226), '_citations': [RFC(3229)], 'description': 'IM Used'},
 {'_': StatusCode(300),
  '_citations': [RFC(7231, section=(6, 4, 1))],
  'description': 'Multiple Choices'},
 {'_': StatusCode(301),
  '_citations': [RFC(7231, section=(6, 4, 2))],
  'description': 'Moved Permanently'},
 {'_': StatusCode(302),
  '_citations': [RFC(7231, section=(6, 4, 3))],
  'description': 'Found'},
 {'_': StatusCode(303),
  '_citations': [RFC(7231, section=(6, 4, 4))],
  'description': 'See Other'},
 {'_': StatusCode(304),
  '_citations': [RFC(7232, section=(4, 1))],
  'description': 'Not Modified'},
 {'_': StatusCode(305),
  '_citations': [RFC(7231, section=(6, 4, 5))],
  'description': 'Use Proxy'},
 {'_': StatusCode(306),
  '_citations': [RFC(7231, section=(6, 4, 6))],
  'description': '(Unused)'},
 {'_': StatusCode(307),
  '_citations': [RFC(7231, section=(6, 4, 7))],
  'description': 'Temporary Redirect'},
 {'_': StatusCode(308),
  '_citations': [RFC(7538)],
  'description': 'Permanent Redirect'},
 {'_': StatusCode(400),
  '_citations': [RFC(7231, section=(6, 5, 1))],
  'description': 'Bad Request'},
 {'_': StatusCode(401),
  '_citations': [RFC(7235, section=(3, 1))],
  'description': 'Unauthorized'},
 {'_': StatusCode(402),
  '_citations': [RFC(7231, section=(6, 5, 2))],
  'description': 'Payment Required'},
 {'_': StatusCode(403),
  '_citations': [RFC(7231, section=(6, 5, 3))],
  'description': 'Forbidden'},
 {'_': StatusCode(404),
  '_citations': [RFC(7231, section=(6, 5, 4))],
  'description': 'Not Found'},
 {'_': StatusCode(405),
  '_citations': [RFC(7231, section=(6, 5, 5))],
  'description': 'Method Not Allowed'},
 {'_': StatusCode(406),
  '_citations': [RFC(7231, section=(6, 5, 6))],
  'description': 'Not Acceptable'},
 {'_': StatusCode(407),
  '_citations': [RFC(7235, section=(3, 2))],
  'description': 'Proxy Authentication Required'},
 {'_': StatusCode(408),
  '_citations': [RFC(7231, section=(6, 5, 7))],
  'description': 'Request Timeout'},
 {'_': StatusCode(409),
  '_citations': [RFC(7231, section=(6, 5, 8))],
  'description': 'Conflict'},
 {'_': StatusCode(410),
  '_citations': [RFC(7231, section=(6, 5, 9))],
  'description': 'Gone'},
 {'_': StatusCode(411),
  '_citations': [RFC(7231, section=(6, 5, 10))],
  'description': 'Length Required'},
 {'_': StatusCode(412),
  '_citations': [RFC(7232, section=(4, 2))],
  'description': 'Precondition Failed'},
 {'_': StatusCode(413),
  '_citations': [RFC(7231, section=(6, 5, 11))],
  'description': 'Payload Too Large'},
 {'_': StatusCode(414),
  '_citations': [RFC(7231, section=(6, 5, 12))],
  'description': 'URI Too Long'},
 {'_': StatusCode(415),
  '_citations': [RFC(7231, section=(6, 5, 13)), RFC(7694, section=(3,))],
  'description': 'Unsupported Media Type'},
 {'_': StatusCode(416),
  '_citations': [RFC(7233, section=(4, 4))],
  'description': 'Range Not Satisfiable'},
 {'_': StatusCode(417),
  '_citations': [RFC(7231, section=(6, 5, 14))],
  'description': 'Expectation Failed'},
 {'_': StatusCode(421),
  '_citations': [RFC(7540, section=(9, 1, 2))],
  'description': 'Misdirected Request'},
 {'_': StatusCode(422),
  '_citations': [RFC(4918)],
  'description': 'Unprocessable Entity'},
 {'_': StatusCode(423), '_citations': [RFC(4918)], 'description': 'Locked'},
 {'_': StatusCode(424),
  '_citations': [RFC(4918)],
  'description': 'Failed Dependency'},
 {'_': StatusCode(426),
  '_citations': [RFC(7231, section=(6, 5, 15))],
  'description': 'Upgrade Required'},
 {'_': StatusCode(428),
  '_citations': [RFC(6585)],
  'description': 'Precondition Required'},
 {'_': StatusCode(429),
  '_citations': [RFC(6585)],
  'description': 'Too Many Requests'},
 {'_': StatusCode(431),
  '_citations': [RFC(6585)],
  'description': 'Request Header Fields Too Large'},
 {'_': StatusCode(451),
  '_citations': [],
  'description': 'Unavailable for Legal Reasons'},
 {'_': StatusCode(500),
  '_citations': [RFC(7231, section=(6, 6, 1))],
  'description': 'Internal Server Error'},
 {'_': StatusCode(501),
  '_citations': [RFC(7231, section=(6, 6, 2))],
  'description': 'Not Implemented'},
 {'_': StatusCode(502),
  '_citations': [RFC(7231, section=(6, 6, 3))],
  'description': 'Bad Gateway'},
 {'_': StatusCode(503),
  '_citations': [RFC(7231, section=(6, 6, 4))],
  'description': 'Service Unavailable'},
 {'_': StatusCode(504),
  '_citations': [RFC(7231, section=(6, 6, 5))],
  'description': 'Gateway Timeout'},
 {'_': StatusCode(505),
  '_citations': [RFC(7231, section=(6, 6, 6))],
  'description': 'HTTP Version Not Supported'},
 {'_': StatusCode(506),
  '_citations': [RFC(2295)],
  'description': 'Variant Also Negotiates'},
 {'_': StatusCode(507),
  '_citations': [RFC(4918)],
  'description': 'Insufficient Storage'},
 {'_': StatusCode(508),
  '_citations': [RFC(5842)],
  'description': 'Loop Detected'},
 {'_': StatusCode(510),
  '_citations': [RFC(2774)],
  'description': 'Not Extended'},
 {'_': StatusCode(511),
  '_citations': [RFC(6585)],
  'description': 'Network Authentication Required'}
 ],
 extra_info=['description']
)
