# -*- coding: utf-8; -*-

from httpolice.citation import RFC
from httpolice.known.base import KnownDict
from httpolice.structure import StatusCode


known = KnownDict([
 {'_': StatusCode(100),
  '_citations': [RFC(7231, section=(6, 2, 1))],
  '_title': 'Continue'},
 {'_': StatusCode(101),
  '_citations': [RFC(7231, section=(6, 2, 2))],
  '_title': 'Switching Protocols'},
 {'_': StatusCode(102),
  '_citations': [RFC(2518)],
  '_title': 'Processing'},
 {'_': StatusCode(200),
  '_citations': [RFC(7231, section=(6, 3, 1))],
  '_title': 'OK'},
 {'_': StatusCode(201),
  '_citations': [RFC(7231, section=(6, 3, 2))],
  '_title': 'Created'},
 {'_': StatusCode(202),
  '_citations': [RFC(7231, section=(6, 3, 3))],
  '_title': 'Accepted'},
 {'_': StatusCode(203),
  '_citations': [RFC(7231, section=(6, 3, 4))],
  '_title': 'Non-Authoritative Information'},
 {'_': StatusCode(204),
  '_citations': [RFC(7231, section=(6, 3, 5))],
  '_title': 'No Content'},
 {'_': StatusCode(205),
  '_citations': [RFC(7231, section=(6, 3, 6))],
  '_title': 'Reset Content'},
 {'_': StatusCode(206),
  '_citations': [RFC(7233, section=(4, 1))],
  '_title': 'Partial Content'},
 {'_': StatusCode(207),
  '_citations': [RFC(4918)],
  '_title': 'Multi-Status'},
 {'_': StatusCode(208),
  '_citations': [RFC(5842)],
  '_title': 'Already Reported'},
 {'_': StatusCode(226), '_citations': [RFC(3229)], '_title': 'IM Used'},
 {'_': StatusCode(300),
  '_citations': [RFC(7231, section=(6, 4, 1))],
  '_title': 'Multiple Choices'},
 {'_': StatusCode(301),
  '_citations': [RFC(7231, section=(6, 4, 2))],
  '_title': 'Moved Permanently'},
 {'_': StatusCode(302),
  '_citations': [RFC(7231, section=(6, 4, 3))],
  '_title': 'Found'},
 {'_': StatusCode(303),
  '_citations': [RFC(7231, section=(6, 4, 4))],
  '_title': 'See Other'},
 {'_': StatusCode(304),
  '_citations': [RFC(7232, section=(4, 1))],
  '_title': 'Not Modified'},
 {'_': StatusCode(305),
  '_citations': [RFC(7231, section=(6, 4, 5))],
  '_title': 'Use Proxy'},
 {'_': StatusCode(306),
  '_citations': [RFC(7231, section=(6, 4, 6))],
  '_title': '(Unused)'},
 {'_': StatusCode(307),
  '_citations': [RFC(7231, section=(6, 4, 7))],
  '_title': 'Temporary Redirect'},
 {'_': StatusCode(308),
  '_citations': [RFC(7538)],
  '_title': 'Permanent Redirect'},
 {'_': StatusCode(400),
  '_citations': [RFC(7231, section=(6, 5, 1))],
  '_title': 'Bad Request'},
 {'_': StatusCode(401),
  '_citations': [RFC(7235, section=(3, 1))],
  '_title': 'Unauthorized'},
 {'_': StatusCode(402),
  '_citations': [RFC(7231, section=(6, 5, 2))],
  '_title': 'Payment Required'},
 {'_': StatusCode(403),
  '_citations': [RFC(7231, section=(6, 5, 3))],
  '_title': 'Forbidden'},
 {'_': StatusCode(404),
  '_citations': [RFC(7231, section=(6, 5, 4))],
  '_title': 'Not Found'},
 {'_': StatusCode(405),
  '_citations': [RFC(7231, section=(6, 5, 5))],
  '_title': 'Method Not Allowed'},
 {'_': StatusCode(406),
  '_citations': [RFC(7231, section=(6, 5, 6))],
  '_title': 'Not Acceptable'},
 {'_': StatusCode(407),
  '_citations': [RFC(7235, section=(3, 2))],
  '_title': 'Proxy Authentication Required'},
 {'_': StatusCode(408),
  '_citations': [RFC(7231, section=(6, 5, 7))],
  '_title': 'Request Timeout'},
 {'_': StatusCode(409),
  '_citations': [RFC(7231, section=(6, 5, 8))],
  '_title': 'Conflict'},
 {'_': StatusCode(410),
  '_citations': [RFC(7231, section=(6, 5, 9))],
  '_title': 'Gone'},
 {'_': StatusCode(411),
  '_citations': [RFC(7231, section=(6, 5, 10))],
  '_title': 'Length Required'},
 {'_': StatusCode(412),
  '_citations': [RFC(7232, section=(4, 2))],
  '_title': 'Precondition Failed'},
 {'_': StatusCode(413),
  '_citations': [RFC(7231, section=(6, 5, 11))],
  '_title': 'Payload Too Large'},
 {'_': StatusCode(414),
  '_citations': [RFC(7231, section=(6, 5, 12))],
  '_title': 'URI Too Long'},
 {'_': StatusCode(415),
  '_citations': [RFC(7231, section=(6, 5, 13)), RFC(7694, section=(3,))],
  '_title': 'Unsupported Media Type'},
 {'_': StatusCode(416),
  '_citations': [RFC(7233, section=(4, 4))],
  '_title': 'Range Not Satisfiable'},
 {'_': StatusCode(417),
  '_citations': [RFC(7231, section=(6, 5, 14))],
  '_title': 'Expectation Failed'},
 {'_': StatusCode(421),
  '_citations': [RFC(7540, section=(9, 1, 2))],
  '_title': 'Misdirected Request'},
 {'_': StatusCode(422),
  '_citations': [RFC(4918)],
  '_title': 'Unprocessable Entity'},
 {'_': StatusCode(423), '_citations': [RFC(4918)], '_title': 'Locked'},
 {'_': StatusCode(424),
  '_citations': [RFC(4918)],
  '_title': 'Failed Dependency'},
 {'_': StatusCode(426),
  '_citations': [RFC(7231, section=(6, 5, 15))],
  '_title': 'Upgrade Required'},
 {'_': StatusCode(428),
  '_citations': [RFC(6585)],
  '_title': 'Precondition Required'},
 {'_': StatusCode(429),
  '_citations': [RFC(6585)],
  '_title': 'Too Many Requests'},
 {'_': StatusCode(431),
  '_citations': [RFC(6585)],
  '_title': 'Request Header Fields Too Large'},
 {'_': StatusCode(451),
  '_citations': [],
  '_title': 'Unavailable for Legal Reasons'},
 {'_': StatusCode(500),
  '_citations': [RFC(7231, section=(6, 6, 1))],
  '_title': 'Internal Server Error'},
 {'_': StatusCode(501),
  '_citations': [RFC(7231, section=(6, 6, 2))],
  '_title': 'Not Implemented'},
 {'_': StatusCode(502),
  '_citations': [RFC(7231, section=(6, 6, 3))],
  '_title': 'Bad Gateway'},
 {'_': StatusCode(503),
  '_citations': [RFC(7231, section=(6, 6, 4))],
  '_title': 'Service Unavailable'},
 {'_': StatusCode(504),
  '_citations': [RFC(7231, section=(6, 6, 5))],
  '_title': 'Gateway Timeout'},
 {'_': StatusCode(505),
  '_citations': [RFC(7231, section=(6, 6, 6))],
  '_title': 'HTTP Version Not Supported'},
 {'_': StatusCode(506),
  '_citations': [RFC(2295)],
  '_title': 'Variant Also Negotiates'},
 {'_': StatusCode(507),
  '_citations': [RFC(4918)],
  '_title': 'Insufficient Storage'},
 {'_': StatusCode(508),
  '_citations': [RFC(5842)],
  '_title': 'Loop Detected'},
 {'_': StatusCode(510),
  '_citations': [RFC(2774)],
  '_title': 'Not Extended'},
 {'_': StatusCode(511),
  '_citations': [RFC(6585)],
  '_title': 'Network Authentication Required'}
 ],
 name_from_title=True
)
