#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import os
import sys

import httpolice


def main():
    parser = argparse.ArgumentParser(
        description=u'Run HTTPolice on streams collected by tcpick.')
    parser.add_argument(u'-H', u'--html', action=u'store_true',
                        help=u'render HTML report instead of plain text')
    parser.add_argument(u'--only-with-notices', action=u'store_true',
                        help=u'exclude connections that have no notices')
    parser.add_argument(u'streams_dir')
    args = parser.parse_args()

    inputs = []
    for name in os.listdir(args.streams_dir):
        if ('.serv.' not in name) or (not name.endswith('.dat')):
            continue
        _, n, _ = name.rsplit('.', 2)
        if n.isdigit():
            n = int(n)
        else:
            n = 0
        inbound = os.path.join(args.streams_dir, name)
        outbound = os.path.join(args.streams_dir,
                                name.replace('.serv.', '.clnt.'))
        if not os.path.exists(outbound):
            sys.stderr.write('No outbound stream %s, skipping' %
                             os.path.basename(outbound))
            continue
        inputs.append((inbound, outbound, (os.stat(inbound).st_ctime, n)))

    inputs.sort(key=lambda entry: entry[2])

    result = []
    for inbound, outbound, _ in inputs:
        with open(inbound) as f:
            inbound_stream = f.read()
        with open(outbound) as f:
            outbound_stream = f.read()
        conn = httpolice.analyze_streams(inbound_stream, outbound_stream,
                                         scheme=u'http')
        if (not args.only_with_notices) or any(conn.collect_complaints()):
            result.append(conn)

    if args.html:
        report_cls = httpolice.HTMLReport
    else:
        report_cls = httpolice.TextReport
    report_cls.render(result, sys.stdout)

if __name__ == '__main__':
    sys.exit(main())
